version: "3.3"

services:
    postgresTrackV:
        image: postgres
        container_name: db
        restart: always
        ports:
            - 5432
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./db:/var/lib/postgresql/data

    pgadminTrackV:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - 5050:80
      depends_on:
        - postgresTrackV
